spring.application.name=YouTube

spring.datasource.url=jdbc:postgresql://localhost:5432/YouTube_db
spring.datasource.username=postgres
spring.datasource.password=1065
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
server.url=http://localhost:${server.port}

#########################
#        Mail
#########################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=fboqiyev1065@mail.ru
spring.mail.password=HV8v58lE8jqoGQD6g7RC
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
